name = "Project SkyBlock"
author = "null2264"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b803ec1e218422aaefc86fc16e0be8dc983481206b3f1da263d8d7926e909476"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
