name = "Project SkyBlock"
author = "null2264"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf2c1bfb7864064833e6516455f73954ce9523a677ba61659505725cade03d83"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
